site_name: CAM tools
nav:
    - Main Page: 'index.md'
    - Cognitive-Affective Maps: 'Cognitive-Affective Maps.md'
    - Set up study: 'Set up study.md'
    - Data Collection Tool: 'Data Collection Tool.md'
    - Data Analysis Tool: 'Data Analysis Tool.md'
    - Support: 'Support.md'
    - Additional Resources: 'Additional Resources.md'
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - bibtex:
      bib_file: 'MyLibrary.bib'
      bib_by_default: true
      #csl_file: './docs/apa-6th-edition.csl'
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - footnotes

